configs/mesos_example.yaml, owca/cgroups.py, owca/containers.py, owca/resctrl.py
Fixing https://github.com/intel/owca/issues/25.
Tested on a real cluster, by stopping run by the debugger, killing mesos jobs and rerunning the application.
=> Fix race condition: the mesos task killed during runner iteration loop.

owca/allocators.py, owca/logger.py, tests/test_allocations.py, tests/test_perf.py
Includes all the necessary components for enable allocation:
- base module and no-op implementation
- encoding metrics for allocations
- required function to operator on RDTAllocation objects
=> allocation: Allocators module

owca/perf.py, owca/security.py, tests/test_perf.py
=> Fix intendation, remove prints and add SetEffectiveRootUid for perf

docs/allocation.rst, owca/extra/static_allocator.py, owca/resctrl.py, owca/resctrl_allocations.py, owca/runners/allocation.py, owca/runners/detection.py, owca/runners/measurement.py, owca/testing.py, tests/runners/test_runners_allocation.py, tests/runners/test_runners_allocation_helpers.py, tests/runners/test_runners_detection.py, tests/runners/test_runners_measurement.py
Reconfigure log levels to follow convention that:
- info should be used in iterations
=> Static allocator better logs and fix mb control initialization.

Pipfile, Pipfile.lock
Due to security, it is necessary to update the package
=> Upgrade urllib3

Pipfile, Pipfile.lock, owca/databases.py, tests/test_databases.py
To be used as a central storage for global configuration for whole cluster.
TODO:
=> Database abstraction for etcd/zookeeper.

Jenkinsfile
params variable should be upper case
=> Fix build images conditional

owca/extra/static_allocator.py
Bug: every call new rules from file were appended instead of being just loaded.
=> Fix static allocations rules merging

wca/platforms.py
During RDT refactoring, but was introduced that was assuming that MB is read from dedicated directory, meanwhile MB monitoring is in the same directory as L3.
=> Fix RDT cache and MBM monitoring is discovered

tests/runners/test_runners_allocation.py, tests/runners/test_runners_allocation_helpers.py, wca/resctrl_allocations.py, wca/runners/allocation.py, wca/testing.py
MBA allocations are not properly validated 
(/sys/fs/resctrl/info/MB/min_bandwidth) is not taken into consideration
=> MBA allocations validate fix

wca/mesos.py
Catch exception when pid not exist when create Mesos task and not create Mesos task for this reason. https://github.com/intel/workload-collocation-agent/issues/154
=> Catch exception when pid not exist when create Mesos task

README.rst, docs/ssl.rst, wca/config.py, wca/databases.py, wca/security.py
Better exceptions, better docs and fix kazoo client (it wasn't possible to disable verify_certs)
=> SSL object quick fixes and docs

tests/test_databases.py, wca/databases.py
This PR fix issues:
#160 
#159 
#158
=> Database fix

Pipfile, Pipfile.lock
No update for confluent_kafka because of https://github.com/confluentinc/confluent-kafka-python/issues/482#issuecomment-490711109
=> Update dependecies to latest versions

README.rst
=> Update README.rst - fixes in getting started (#171)

Jenkinsfile, tests/tester/configs/tester_config.yaml, tests/tester/configs/tester_example.yaml, tests/tester/tester.py
As Mesos integration developer I want to have integration tests for perf counters handling developed so that it is possible to assure correct behavior of the component.
=> Perf counters integration tests

example/http_storage.py, tests/test_security.py, wca/databases.py, wca/perf.py, wca/resctrl.py, workloads/common.py
While security review of code found minor issues with code style among the project. This PR fixes all of them.
=> Minor fixes of coding style.

Pipfile, Pipfile.lock
urrlib3 is a requirement of requests library and there is no need
to state it in Pipfile.
=> Remove urllib3 from Pipfile.

docs/kubernetes.rst
=> Fix a broken link in Kubernetes docs.

tests/e2e/demo_scenarios/common/wca_config_mesos.yaml, tests/test_kubernetes.py, wca/kubernetes.py
* Fix build cgroup path for systemd in Kubernetes
* Changed MesosNode IP for e2e tests
=> Fix build cgroup path for systemd in Kubernetes (#307)

tests/test_security.py, wca/runners/allocation.py, wca/runners/measurement.py, wca/security.py
WCA should work if no privileges are needed.
=> Fix checking sufficient privileges.

wca/main.py
Backported from 985ed5f
Fixes #320 for ``1.0.x`` branch
=> Fix loggers configuration precedance (from command line and config file)

wca/runners/allocation.py
Fixing null pointer dereference issue identified by Coverity.
=> Getting rid of null pointer dereference

docs/api.rst, docs/numa_allocator.rst, wca/allocations.py, wca/extra/numa_allocator.py
https://github.com/felidadae/workload-collocation-agent/blob/sbugaj/numa_allocator_rst_doc/docs/api.rst#numaallocator to see rendered rst
=> Add docs/numa_allocator.rst

docs/logging.rst, wca/main.py
=> Fix improper loggers configuration precedence.

Dockerfile.kafka, Jenkinsfile, Makefile, Pipfile, Pipfile.lock, docs/development.rst, setup.py, tests/storage/test_storage.py
Also:
- remove option to build confluent_kafka directly from Pipenv
- add functionality to build wrappers in docker
=> Update confluent_kafka dependency to 1.2

docs/logging.rst, wca/main.py
=> Fix improper loggers configuration precedence for 1.0.x

Jenkinsfile
After merge you can test your image like this:
```
docker pull 100.64.176.12:80/wca:PR-369
docker pull 100.64.176.12:80/wca:PR-369-devel
```
=> Tag WCA with branch name and restore fail fast.

wca/platforms.py, wca/runners/measurement.py
None will be default, which means collect if possible
=> Make gather_hw_mm_topology automatically enabled 

tests/test_pmembw.py, wca/pmembw.py
Fixed socket label in metric and value GB multiplier.
=> Fix pmembw

docs/metrics.csv, docs/metrics.rst, tests/runners/test_runners_measurement.py, wca/containers.py, wca/metrics.py, wca/runners/measurement.py
Add a new metric for measuring number of sub-containers in Task.
=> Fix syncing Task's sub-containers state for Kubernetes.

.gitignore, Dockerfile, tests/test_platforms.py, wca/platforms.py
when containing just newline escape character
=> Bugfix to handle empty listformat and fix dmidecode

examples/kubernetes/monitoring/fluentd/daemonset.yaml
=> Fix OOM of fluentd

tests/test_wss.py, wca/containers.py, wca/runners/measurement.py, wca/wss.py
Update tests. Better naming. Add interval to ContainerManager.
=> Fixes in WSS

docs/api.rst, tests/test_wss.py, tests/tester/configs/tester_config.yaml, wca/containers.py, wca/extra/numa_allocator.py, wca/runners/measurement.py, wca/wss.py
and passing missing interval.
Additionally expose "threshold divider" as configurable parameter.
Logs were improved to show for what pids the wss is calculated.
=> Fix WSS membw calculation (double call) 

Jenkinsfile, examples/kubernetes/monitoring/cadvisor/Dockerfile.cadvisor, examples/kubernetes/monitoring/cadvisor/README.rst
Signed-off-by: Katarzyna Kujawa <katarzyna.kujawa@intel.com>
=> Modify dockerfile for cAdvisor to build from fork

docs/score_algorithm.rst
- Mention possible overstime of WSS effect on huge pages/THP enabled servers,
- 2LM is also know and official name is "Memory Mode"
- HMEM is alson know and branded as "memory tiering"
- explain why changes to rules are required for HMEM
=> Miner fixes to score_algorithm docs.

examples/kubernetes/monitoring/cadvisor/README.rst
Signed-off-by: Katarzyna Kujawa <katarzyna.kujawa@intel.com>
=> Fix docker run command to collect referenced bytes using cAdvisor
