intel/workload-collocation-agent

owca/detectors.py, owca/mesos.py, owca/nodes.py, owca/runner.py, owca/testing.py, tests/test_main.py, tests/test_mesos.py
Rationale:
- **abstractproperty** were used improperly 
- **abstractproperty** can only enforce method based "property" not the normal one, that is way **MesosTask** couldn't properly iherit from it
Now Task dataclass is enough and Node implementation have no create owns Task implementation and can just reuse existing dataclass.
Quirks:
- in MesosTask we still have to create __hash__ classes because how dataclass treat __hash__ method ([here is explanation](https://github.com/python/cpython/blob/3.7/Lib/dataclasses.py#L118))
- base Task class cannot have default properties (e.g. labels or resources) - because then all inherited class need to have all fields optional (check [this ](https://stackoverflow.com/questions/51575931/class-inheritance-in-python-3-7-dataclasses)fur further …
=> Replace improper Task abstract class with dataclass

owca/testing.py, tests/test_testing.py
two functions:
- `assert_metric` - metrics with matching labels existing in given list and value optionally equals (used for testing for some metrics in `storage.store` calls)
- `assert_subdict` - on dict is a subdict of another in recursive manner (used for testing that `detect`/`allocate` got right data
=> Check metrics exists in list of metrics include labels submatch tooling.

workloads/run_workloads_inventory.template.yaml
Fix how to overwrite choosen keys in workloads dictionary (needed default subdictionary).
=> Fix in run_workloads template file.

configs/extra/static_measurements_with_extra_metrics.yaml, docs/allocation.rst, owca/containers.py, owca/extra/static_node.py, owca/metrics.py, owca/perf.py, owca/perf_const.py, owca/runners/allocation.py, owca/runners/detection.py, owca/runners/measurement.py, owca/testing.py, tests/extra/test_static_node.py, tests/test_containers.py, tests/test_perf.py
Ability to specify which perf events to collection including own raw events from config file.
raw event format is as follows: NAME__rEEUUCC 
where:
- EE - event selector
- UU - unit mask
- CC - counter mask (optionall)
Additional feature:
- static_node may now check if there any pids before returning tasks (to not return empty cgroups)
=> Configurable perf events (support for raw and predefined dervied events)

owca/resctrl_allocations.py, owca/runners/allocation.py, tests/resctrl/test_resctrl_allocations.py
Two fixes:
- do not detect change if 'rdt value' (both l3 or mb) is left prefixed with either ' ' or '0' (this is how schemata write works)
- allow to specify just one domain to update (do not require all) and add domain id validation
=> Fix mb schemata write for RDT.

owca/kubernetes.py, owca/mesos.py, owca/platforms.py, owca/runners/measurement.py, tests/runners/test_runners_measurement.py, tests/test_platforms.py
Add additional label with cpu initial assignment, to simplify
management of distributed model system for plugin:
https://github.com/intel/platform-resource-manager/tree/master/prm
Its workaround and that solution should be removed. But it seems
that to make a proper solution the API needs to be changed.
=> Add two additional metrics labels cpu_model and initial_task_cpu.

tests/extra/test_static_node.py, wca/extra/static_node.py
Some plugins like PRM, require resources to be provided. To be able to test those, this commit 
allows to specify dummy default labels and resource to be returned by static node for all tasks.
Can be further extend to specify tasks specific labels/resource in follow up PR.
=> Allow to provide default labels and resources for StaticNode

wca/databases.py
@yiliyl " so for etcd 3.3.x version, we can use the api_path '/v3beta' or '/v3' "
=> Add etcd api path available to set

tests/runners/test_runners_measurement.py, wca/runners/measurement.py
The last iteration property in runner was improperly set to moment before sleep, so nest iteration sleep was skipped. The result was that wca iterations were called twice more than expected. PR include tests.
=> Fix time wait/action delay

tests/test_security.py, wca/security.py
Certifcates and keys cannot be described by their extension. Also there are more types of encodings...
=> Fix handling PEM in SSL

wca/perf.py
For situation that perf subsystem is shared among many applications measurements scaling warning is to verbose and we've already dedicated metrics to inform about scaling issues, called:
- `scaling_factor_avg`
- `scaling_factor_max`
After warning is removed the operator is responsible to watch over those metrics and react if values are to high.
=> Replace scaling warning with debug entry

Pipfile.lock, tests/test_mesos.py, wca/containers.py, wca/mesos.py, wca/resctrl.py
In case that cgroup path derived from executor process (by its pid) is set to root cgroup, 
ignore such tasks with proper warning and handle that cases in finally clause for synchronizing pids for resctrl.
If this warning happens every iteration for every tasks, it means that unsupported Mesos or its executor/containerizer configuration is in use.
If warning happens rarely, may indicate races when mesos job is initialized.
=> Handle missing cgroup for Mesos executor process

docs/kubernetes.rst
URL was broken for the example daemonset.
Signed-off-by: Eric Ernst <eric.ernst@intel.com>
=> docs: update broken url in kubernetes.rst

docs/install.rst, tests/test_security.py, wca/runners/measurement.py, wca/security.py
We missed that DAC_OVERRIDE and SETUID capabilities are required also for cpu type discovery,
so there was misleading privileges check error message that suggested some of privileges only required of RDT enabled.
Additionally SETUID and additional secure bit (docs update) is required for switching back to unprivileged user without loosing those two capabilities.
=> Better docs and handling of insufficient privileges.

tests/resctrl/test_resctrl_allocations.py, tests/runners/test_runners_allocation_helpers.py, wca/platforms.py, wca/resctrl_allocations.py, wca/runners/allocation.py
> The allocated b/w percentage is rounded off to the next control step available on the hardware. The
available bandwidth control steps are: min_bandwidth + N * bandwidth_gran.
Source: `https://www.kernel.org/doc/Documentation/x86/intel_rdt_ui.txt`
=> Fix problem with MB RDT allocations granularity.

Jenkinsfile, docs/extending.rst
User `PYTHONPATH` should not be prefered in pex file.
=> Fix `PEX_INHERIT_PATH` flag for integration tests.

wca/perf.py
Missing `FileNotFound` excpetion during cgroup based perf initialization.
=> Handle missing container race for perf/cgroup based metrics.

tests/e2e/demo_scenarios/common/wca_config_mesos.yaml, tests/test_kubernetes.py, wca/kubernetes.py
Cgroup path for cgroup driver systemd for Kubernetes was built in incorrect way. I've added fix and tests. The changes was tested on Kubernetes 1.15 and 1.16.
=> Fix build cgroup path for systemd in Kubernetes

tests/test_cgroups_allocations.py, tests/test_platforms.py, tests/testing.py, wca/cgroups_allocations.py, wca/platforms.py
It causes OOM kills if there is not enough memory.
=> Check if swap is disabled before using migrate_pages allocation.

Jenkinsfile, tests/test_perf.py, wca/perf.py, wca/runners/measurement.py
1. During E2E tests, echa build image will have name of branch as tag
2. Upon starting WCA, perform a check to make sure that there is enough PMU counters available  (assuming 8 for non-ht and 4 for ht enabled platforms, verified on BDX, SKX and CLX)
=> Tag images create by WCA with branch name and check that there is enough available PMU counters.

tests/runners/test_runners_allocation.py, tests/runners/test_runners_detection.py, tests/runners/test_runners_measurement.py, tests/test_containers.py, tests/testing.py, wca/cgroups.py, wca/containers.py
The root cause is that WCA sum counters, before rate and generally the only valid operation is rate first.
https://www.robustperception.io/rate-then-sum-never-sum-then-rate
This workaround should solve the issue of spike in rates for cpuacct.usage, but generally the proper solution would be exposing metrics per container.
=> Workaround for broken cpuacct.usage counter from multi container Pods

wca/cgroups.py
Cgroups `cpuacct.usage` is a counter, so it should be threatened as decimal number.
=> Counter "cpuacct.usage" conversion fix.

examples/kubernetes/wca-scheduler/wca-scheduler-deployment.yaml
This can cause some problems (e.g. until pod terminating is done, new pods gets "PodFitsHostPorts" status due to the port using)
=> Fix wca-scheduler deployment

examples/kubernetes/monitoring/prometheus/2lm_score_dashboard.json, examples/kubernetes/monitoring/prometheus/kustomization.yaml, examples/kubernetes/monitoring/prometheus/prometheus_rule.score.yaml
Provides a intermediate and final metrics to calaculating score for 2LM average node.   
List of metrics:
- For nodes (**dim**=[cpu, mem, wss, mbw_write, mbw_read]) and following units: cpu, GB, GB, GBs, GBs
- `node_capacity`
- `profile_nodes_by_cpu` with index=[mem_density, mem_intensity_read, mem_intensity_write, mem_utilization] 
- `profile_nodes_by_cpu` with memory=[1lm, 2lm]
- For applications
- `app_count`
- low level metrics # WARNING all level metrics take an average of 1d for tasks - need to be modified to shorter time before production use
- `app_cpu`, `app_cpu_usage` [cpu] -> `app_cpu_util` [%]
- `app_mem`, app_mem_usage` [GB]-> `app_mem_util` [%]
- `app_mbw` [GBs], `app_mbw_rw` [%s], `app_mbw_read` [GBs], `app_mbw_write` [GBs]
- `app_wss` [GB]
- all above metrics are put into …
=> Rules for new 2LM score metric 

examples/workloads/cassandra_stress/Dockerfile
By default, Ubuntu or Debian based "apt" or "apt-get" system installs recommended but not suggested packages .
By passing "--no-install-recommends" option, the user lets apt-get know not to consider recommended packages as a dependency to install.
This results in smaller downloads and installation of packages .
Refer to blog at [Ubuntu Blog](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) .
Signed-off-by: Pratik Raj <rajpratik71@gmail.com>
=> Some debian package manager tweaks

examples/kubernetes/monitoring/prometheus/prometheus_rule.score.yaml, examples/kubernetes/wca-scheduler/config.yaml
Modify config after retuning.
Set Score2 as default.
cpu_density was lacking in calculations.
=> Fix bug in calculating Score2 in prometheus rules. 

examples/kubernetes/monitoring/prometheus/prometheus_rule.apm.yaml
It is collecting TPM (Transaction Per Minute) and it is necessary to change minutes to seconds to collect ops. I set dividing by 60 in prometheus metric apm_hammerdb_ops to get ops.
The second solution is to move python script to bash script in the pod, to get more flexibility in defining collecting metric.
=> Change prometheus metric apm_hammerdb_ops

examples/kubernetes/monitoring/prometheus/prometheus_rule.pmem.yaml, examples/kubernetes/monitoring/prometheus/prometheus_rule.score.yaml
Similar to https://github.com/intel/workload-collocation-agent/pull/512
to make it possible to use both wca/cadvisor rules in the same time on a single cluster.
=> Update rules with labels.

tests/test_wss.py, wca/containers.py, wca/wss.py
MBW value was calculated with pod granularity, move WSS granularity per pod level.
Additionally ignore first measurement (without reset), because WCA see the
=> Fix WSS measure per pod rather than container

wca/containers.py
Current method only measures sched stats of main thread (starting threads but ignores all children threads).
=> Fix sched debug stats - collect per thread basis
